name: 'MGCCLI Tests'
description: 'Executa testes para mgccli usando Poetry e Pytest'
author: 'MagaluCloud'

inputs:
  python-version:
    description: 'Versão do Python a ser utilizada'
    required: false
    default: '3.12'
  pytest-args:
    description: 'Argumentos adicionais para passar ao pytest'
    required: false
    default: ''

outputs:
  test-output:
    description: 'Output completo dos testes'
    value: ${{ steps.run-tests.outputs.test-output }}
  test-result:
    description: 'Resultado dos testes (success/failure)'
    value: ${{ steps.run-tests.outputs.test-result }}
  test-summary:
    description: 'Resumo dos testes executados'
    value: ${{ steps.run-tests.outputs.test-summary }}

runs:
  using: 'composite'
  steps:
    - name: Validate environment
      shell: bash
      run: |
        if [ -z "$MGC_API_KEY" ]; then
          echo "❌ MGC_API_KEY não está definida"
          exit 1
        fi
        if [ -z "$MGC_PATH" ]; then
          echo "❌ MGC_PATH não está definida"
          exit 1
        fi
        echo "✅ Variáveis de ambiente validadas"
        
    - name: Resolve MGC_PATH
      shell: bash
      run: |
        # Se MGC_PATH é relativo, converte para absoluto baseado no workspace
        if [[ "$MGC_PATH" != /* ]]; then
          export MGC_PATH="${{ github.workspace }}/${MGC_PATH}"
        fi
        echo "MGC_PATH_RESOLVED=$MGC_PATH" >> $GITHUB_ENV
        echo "MGC_PATH resolvido para: $MGC_PATH"
        
    - name: Verify MGC binary
      shell: bash
      run: |
        if [ ! -f "$MGC_PATH_RESOLVED" ]; then
          echo "❌ Binário MGC não encontrado em: $MGC_PATH_RESOLVED"
          echo "Listando arquivos no diretório:"
          ls -la "$(dirname "$MGC_PATH_RESOLVED")" || echo "Diretório não existe"
          exit 1
        fi
        echo "✅ Binário MGC encontrado: $MGC_PATH_RESOLVED"
        
    - name: Checkout mgccli source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: MagaluCloud/mgccli-tests
        path: ./tmp/mgccli-source
        
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
      with:
        python-version: ${{ inputs.python-version }}
        
    - name: Install Poetry
      uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a
      with:
        version: 1.8.4
        
    - name: Install dependencies
      shell: bash
      working-directory: ./tmp/mgccli-source
      run: |
        poetry install --no-interaction
        
    - name: Run tests
      id: run-tests
      shell: bash
      working-directory: ./tmp/mgccli-source
      env:
        MGC_PATH: ${{ env.MGC_PATH_RESOLVED }}
      run: |
        echo "Executando testes com MGC_PATH: $MGC_PATH"
        
        # Executa os testes e captura a saída
        set +e  # Não falha imediatamente em caso de erro
        output=$(poetry run pytest ${{ inputs.pytest-args }} --tb=short --ignore=tests/test_auth.py 2>&1)
        exit_code=$?
        set -e
        
        # Salva o output completo
        echo "test-output<<EOF" >> $GITHUB_OUTPUT
        echo "$output" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        # Determina o resultado
        if [ $exit_code -eq 0 ]; then
          echo "test-result=success" >> $GITHUB_OUTPUT
          echo "✅ Testes executados com sucesso"
        else
          echo "test-result=failure" >> $GITHUB_OUTPUT
          echo "❌ Testes falharam"
        fi
        
        # Extrai resumo (últimas linhas do pytest)
        summary=$(echo "$output" | tail -n 5)
        echo "test-summary<<EOF" >> $GITHUB_OUTPUT
        echo "$summary" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        # Mantém o exit code original
        exit $exit_code