name: 'MGCCLI Tests'
description: 'Executa testes para mgccli usando Poetry e Pytest'
author: 'MagaluCloud'

inputs:
  python-version:
    description: 'Versão do Python a ser utilizada'
    required: false
    default: '3.12'
  pytest-args:
    description: 'Argumentos adicionais para passar ao pytest'
    required: false
    default: ''
  working-directory:
    description: 'Diretório onde executar os testes'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        poetry install --no-interaction

    - name: Run tests
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        poetry run pytest ${{ inputs.pytest-args }}